version: '2'
services:
  application:
    build: .

  web:
    extends: application
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/contributions
    ports:
      - "80:3000"

  tests:
    extends: application
    command: bundle exec guard -g rspec
    volumes:
      - .:/contributions
